name: volume_button_listener
description: A Flutter plugin to listen to system volume button events and control volume UI display.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.unclezs.volume_button_listener
        pluginClass: VolumeButtonListenerPlugin
      ios:
        pluginClass: VolumeButtonListenerPlugin 